 const booksData = [
 {name: 'Beautiful World, Where Are You?', author: "Sally Rooney", image:"assets/beautiful_world.jpeg",blurb:"The work tells the story of Alice Kelleher, an Irish novelist, and her best friend Eileen Lydon, an editor at a literary magazine. In alternating chapters are descriptions of their lives and emails they send each other. The two other important characters are Kellehers new lover Felix Brady, who works at a warehouse, and Lydon's friend Simon Costigan, who works as a policy adviser.[3][5] In The Guardian, Anthony Cummins describes the novel's structure as a 'love quadrangle' between Kelleher and Brady, on the one hand; and Lydon and Costigan, on the other.[6]"},
    {name: "Conversations With Friends", author: "Sally Rooney", image:"assets/convos.jpeg", blurb:"In Dublin, college students Frances (the narrator) and her best friend and ex-girlfriend Bobbi are noticed by Melissa, an essayist and photographer in her late thirties, when they are performing spoken-word poetry. Melissa invites them home, where they meet her husband, Nick, an actor. Their four lives become increasingly entangled as Frances begins an affair with Nick, and Bobbi and Melissa grow closer."},
    {name: "Intermezzo", author: "Sally Rooney", image:"assets/intermezzo.jpg", blurb:"The novel follows Ivan and Peter Koubek, two brothers living in Dublin, in the weeks after the death of their father. Ivan, a 22-year-old former chess prodigy whose once-promising career has stagnated, meets Margaret Kearns, a 36-year-old arts program director, during a chess exhibition at a local arts centre. Their interaction develops into a passionate but discreet relationship, despite Margaret's concerns about their age difference."},
    {name: "Normal People", author: "Sally Rooney", image:"assets/normal_people.jpg", blurb:"The novel follows the complex friendship and relationship between two teenagers from different social classes, Connell and Marianne, who both attend the same secondary school in County Sligo, Ireland, and, later, Trinity College Dublin (TCD). It is set during the post-2008 Irish economic downturn, from 2011 through 2015.[5]"},
    {name: "Tender Is The Flesh", author: "Augustina Bazterica", image:"assets/titf.jpeg", blurb:"The world has fallen into chaos after the 'Transition', an event where a virus that infected animals was found to be deadly to humans. Animals have been slaughtered and burned en masse, forcing the world's population either to go vegan or eat each other. Soon, cannibalism was institutionalized, industrialized, and normalized. Humans bred for consumption are referred to as 'head,' their meat marketed as 'special meat'. Scavengers, who cannot afford the special meat, consume any dead body available."},
    {name: "Twilight", author: "Stephanie Meyer", image:"assets/twilight.jpg", blurb:"Bella Swan moves from Phoenix, Arizona to live with her father in Forks, Washington to allow her mother to travel with her new husband, a minor league baseball player. After moving to Forks, Bella finds herself involuntarily drawn to a mysterious, handsome boy, Edward Cullen and eventually learns that he is a member of a vampire family which drinks animal blood rather than human blood. Edward and Bella fall in love, while James, a sadistic vampire from another coven, is drawn to hunt down Bella. Edward and the other Cullens defend Bella. She escapes to Phoenix, where she is tricked into confronting James, who tries to kill her. She is seriously wounded, but Edward rescues her and they return to Forks."},
 {name:"The Widow",author:"John Grisham",image:"assets/the_wido.jpg",blurb:"When Simon Latch, a lawyer in rural Virginia, is accused of murder, he goes in search of the real killer."},
{name:"Alchemised",author:"SenLinYu",image:"assets/alchemised.jpg",blurb:"After the war, an imprisoned alchemist is sent to a necromancer to recover her lost memories."},
{name:"The Secret of Secrets",author:"Dan Brown",image:"assets/the_secret_of_secrets.jpg",blurb:"As he searches for the missing noetic scientist he has been seeing, Robert Langdon discovers something regarding a secret project."},
{name:"Gone Before Goodbye",author:"Reese Witherspoon",image:"assets/gone_before_goodbye.jpg",blurb:""},
{name:"The Book of Azrael",author:"Amber V. Nicole",image:"assets/the_book_of_azrael.jpg",blurb:"As dangers intensify, an alliance between enemies might be the only thing that can save a world and various realms."},
{name:"The Intruder",author:"Freida McFadden",image:"assets/the_intruder.jpg",blurb:"During a rough storm, Casey puts herself in danger when she lets a girl, who is covered in blood, into her cabin."},
{name:"Quicksilver",author:"Callie Hart",image:"assets/quicksilver.jpg",blurb:"Saeris is transported to a dangerous land of ice and snow, where she must contend with a Fae warrior who has suspect agendas."},
{name:"Return of the Spider",author:"James Patterson",image:"assets/return_of_the_spider.jpg",blurb:"The 34th book in the Alex Cross series. An enemy’s murder book suggests Cross may have made rookie mistakes years ago."},
{name:"The Correspondent",author:"Virginia Evans",image:"assets/the_correspondent.jpg",blurb:"Letters from someone she used to know push Sybil Van Antwerp toward revisiting her past and finding a way to forgive."},

]

{name:"",author:"",image:"assets/.jpg",blurb:""},